#!/usr/bin/env python3
"""Trusted repository-local historical-ledger publisher for hwm-context.

Candidate/generated bytes are treated as inert blobs: the privileged path never
checks them out, imports them, or executes them.
"""
from __future__ import annotations

import base64
import copy
import hashlib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

REQUEST_SCHEMA = "hwm-historical-ledger-publish-request/v1"
RESULT_SCHEMA = "hwm-historical-ledger-publish-result/v1"
REPOSITORY = "Dsamofalov/hwm-context"
TRANSPORT_ISSUE = 2
ALLOWED_AUTHOR = {"login": "Dsamofalov", "id": 25666939}
RESULT_AUTHOR = {"login": "github-actions[bot]", "id": 41898282}
DEFAULT_BRANCH = "main"
CI_WORKFLOW = "repository-bootstrap-ci.yml"
CI_PATH = ".github/workflows/repository-bootstrap-ci.yml"
REQUIRED_CHECK = "bootstrap"
ALLOWED_PATHS = ("claims/claims.jsonl", "claims/conflicts.json")
BRANCH_PREFIX = "publisher/historical-ledger/"
MAX_BLOB_BYTES = 1024 * 1024
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
REQ_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{7,95}$")
BRANCH_RE = re.compile(r"^publisher/historical-ledger/[a-z0-9][a-z0-9._-]{7,95}$")
FORBIDDEN_PUBLIC_MARKERS = (
    b"-----begin private key-----",
    b"-----begin openssh private key-----",
    b"github_pat_",
    b"ghp_",
    b"authorization: bearer ",
    b"cookie:",
)


class Reject(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = " ".join(message.split())[:240]


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def fingerprint(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def git_blob_sha(data: bytes) -> str:
    return hashlib.sha1(f"blob {len(data)}\0".encode("ascii") + data).hexdigest()


def _sha(value: Any) -> bool:
    return isinstance(value, str) and SHA_RE.fullmatch(value) is not None


def validate_request(obj: Any) -> dict[str, Any]:
    if not isinstance(obj, dict):
        raise Reject("INVALID_SCHEMA", "request must be one JSON object")
    required = {"schema", "request_id", "repository", "transport_issue", "expected_base", "publication_branch", "changes", "ci"}
    if set(obj) != required:
        raise Reject("INVALID_SCHEMA", "request fields do not match historical-ledger-v1")
    if obj.get("schema") != REQUEST_SCHEMA:
        if obj.get("schema") == "hwm-publish-request/bootstrap-v1":
            raise Reject("INVALID_SCHEMA", "bootstrap-v1 is forbidden for hwm-context historical-ledger publication")
        raise Reject("INVALID_SCHEMA", "request schema mismatch")
    if not isinstance(obj.get("request_id"), str) or REQ_RE.fullmatch(obj["request_id"]) is None:
        raise Reject("INVALID_SCHEMA", "request_id is malformed")
    if obj.get("repository") != REPOSITORY:
        raise Reject("REPOSITORY_NOT_ALLOWED", "target repository is not allowlisted")
    if obj.get("transport_issue") != TRANSPORT_ISSUE:
        raise Reject("INVALID_TRANSPORT", "request is not bound to the canonical transport Issue")
    if not _sha(obj.get("expected_base")):
        raise Reject("INVALID_SCHEMA", "expected_base must be exact lowercase 40-hex SHA")
    branch = obj.get("publication_branch")
    if branch in {"main", DEFAULT_BRANCH} or not isinstance(branch, str) or BRANCH_RE.fullmatch(branch) is None:
        raise Reject("FORBIDDEN_TARGET", "publication branch is outside the scoped non-protected namespace")
    changes = obj.get("changes")
    if not isinstance(changes, list) or len(changes) != 2:
        raise Reject("INVALID_SCHEMA", "exactly two canonical output changes are required")
    seen: set[str] = set()
    for change in changes:
        if not isinstance(change, dict):
            raise Reject("INVALID_SCHEMA", "change must be an object")
        op = change.get("op")
        keys = {"op", "path", "blob_sha", "mode"} if op == "add" else {"op", "path", "blob_sha", "mode", "expected_blob_sha"} if op == "replace" else set()
        if not keys or set(change) != keys:
            raise Reject("INVALID_SCHEMA", "change fields/op are invalid")
        path = change.get("path")
        if path not in ALLOWED_PATHS:
            raise Reject("FORBIDDEN_PATH", "only the two canonical historical-ledger outputs are allowed")
        if path in seen:
            raise Reject("INVALID_SCHEMA", "canonical path appears more than once")
        seen.add(path)
        if change.get("mode") != "100644":
            raise Reject("BLOB_NOT_REGULAR", "v1 permits regular mode 100644 only")
        if not _sha(change.get("blob_sha")):
            raise Reject("INVALID_SCHEMA", "blob_sha must be exact lowercase 40-hex SHA")
        if op == "replace" and not _sha(change.get("expected_blob_sha")):
            raise Reject("INVALID_SCHEMA", "replace requires exact expected_blob_sha")
    if seen != set(ALLOWED_PATHS):
        raise Reject("FORBIDDEN_PATH", "request must cover both canonical historical-ledger outputs exactly once")
    if obj.get("ci") != {"workflow": CI_WORKFLOW, "required_check": REQUIRED_CHECK}:
        raise Reject("INVALID_SCHEMA", "CI declaration must name exact bootstrap workflow/check")
    return obj


def validate_public_blob(data: bytes) -> None:
    if len(data) > MAX_BLOB_BYTES or b"\x00" in data:
        raise Reject("UNSAFE_PAYLOAD", "candidate blob violates bounded UTF-8 text policy")
    try:
        data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise Reject("UNSAFE_PAYLOAD", "candidate blob is not UTF-8") from exc
    lowered = data.lower()
    if any(marker in lowered for marker in FORBIDDEN_PUBLIC_MARKERS):
        raise Reject("UNSAFE_PAYLOAD", "candidate blob matches a forbidden credential marker")


class GitHub:
    def __init__(self, token: str):
        self.token = token
        self.base = f"https://api.github.com/repos/{REPOSITORY}"

    def request(self, method: str, path: str, payload: Any | None = None) -> Any:
        data = None if payload is None else canonical_json(payload).encode("utf-8")
        req = urllib.request.Request(self.base + path, data=data, method=method)
        req.add_header("Accept", "application/vnd.github+json")
        req.add_header("X-GitHub-Api-Version", "2022-11-28")
        req.add_header("Authorization", f"Bearer {self.token}")
        if data is not None:
            req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                raw = response.read()
                return None if not raw else json.loads(raw.decode("utf-8"))
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", "replace")[:400]
            raise RuntimeError(f"GitHub API {method} {path} failed with {exc.code}: {body}") from exc

    def comments(self) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        for page in range(1, 11):
            batch = self.request("GET", f"/issues/{TRANSPORT_ISSUE}/comments?per_page=100&page={page}") or []
            out.extend(batch)
            if len(batch) < 100:
                break
        return out


def _comment_json(comment: dict[str, Any]) -> dict[str, Any] | None:
    body = comment.get("body")
    if not isinstance(body, str):
        return None
    try:
        obj = json.loads(body)
    except json.JSONDecodeError:
        return None
    return obj if isinstance(obj, dict) else None


def error_result(request: Any, code: str, message: str, *, fp: str | None = None) -> dict[str, Any]:
    rid = request.get("request_id") if isinstance(request, dict) and isinstance(request.get("request_id"), str) else "invalid-request"
    expected = request.get("expected_base") if isinstance(request, dict) and _sha(request.get("expected_base")) else None
    branch = request.get("publication_branch") if isinstance(request, dict) and isinstance(request.get("publication_branch"), str) else None
    return {
        "schema": RESULT_SCHEMA,
        "request_id": rid,
        "status": "error",
        "repository": REPOSITORY,
        "transport_issue": TRANSPORT_ISSUE,
        "expected_base": expected,
        "publication_branch": branch,
        "request_fingerprint": fp or fingerprint(request),
        "idempotent_replay": False,
        "commit_sha": None,
        "pr_number": None,
        "ci_dispatch": None,
        "error": {"code": code, "message": " ".join(message.split())[:240]},
    }


class Publisher:
    def __init__(self, api: GitHub):
        self.api = api

    def _prior(self, request: dict[str, Any], fp: str, current_comment_id: int | None) -> dict[str, Any] | None:
        for comment in self.api.comments():
            obj = _comment_json(comment)
            if not obj or obj.get("request_id") != request["request_id"]:
                continue
            user = comment.get("user") or {}
            if obj.get("schema") == REQUEST_SCHEMA and comment.get("id") != current_comment_id:
                if user.get("login") == ALLOWED_AUTHOR["login"] and user.get("id") == ALLOWED_AUTHOR["id"] and fingerprint(obj) != fp:
                    raise Reject("REQUEST_ID_REUSE", "request_id was previously used with different normalized payload")
            if obj.get("schema") == RESULT_SCHEMA and user.get("login") == RESULT_AUTHOR["login"]:
                if obj.get("request_fingerprint") != fp:
                    raise Reject("REQUEST_ID_REUSE", "request_id already has a result for different normalized payload")
                replay = copy.deepcopy(obj)
                replay["idempotent_replay"] = True
                return replay
        return None

    def publish(self, event: dict[str, Any]) -> dict[str, Any] | None:
        comment = event.get("comment") or {}
        issue = event.get("issue") or {}
        repo = event.get("repository") or {}
        author = comment.get("user") or {}
        if issue.get("pull_request") or issue.get("number") != TRANSPORT_ISSUE or repo.get("full_name") != REPOSITORY:
            return None
        if author.get("login") != ALLOWED_AUTHOR["login"] or author.get("id") != ALLOWED_AUTHOR["id"]:
            return None
        try:
            raw = json.loads(comment.get("body", ""))
        except json.JSONDecodeError:
            return None
        if isinstance(raw, dict) and raw.get("schema") == RESULT_SCHEMA:
            return None
        try:
            request = validate_request(raw)
            fp = fingerprint(request)
            replay = self._prior(request, fp, comment.get("id"))
            if replay is not None:
                return replay

            ref = self.api.request("GET", "/git/ref/heads/main")
            observed = ((ref or {}).get("object") or {}).get("sha")
            if observed != request["expected_base"]:
                raise Reject("EXPECTED_HEAD_MISMATCH", "protected main does not equal expected_base")
            base_commit = self.api.request("GET", f"/git/commits/{request['expected_base']}") or {}
            tree_sha = (base_commit.get("tree") or {}).get("sha")
            if not _sha(tree_sha):
                raise Reject("INTERNAL_ERROR", "base commit tree is unavailable")
            tree = self.api.request("GET", f"/git/trees/{tree_sha}?recursive=1") or {}
            by_path = {e.get("path"): e for e in tree.get("tree", []) if isinstance(e, dict) and isinstance(e.get("path"), str)}

            for change in request["changes"]:
                current = by_path.get(change["path"])
                if change["op"] == "add":
                    if current is not None:
                        raise Reject("PATH_STATE_MISMATCH", "add target already exists at expected_base")
                else:
                    if not current or current.get("type") != "blob" or current.get("mode") not in {"100644", "100755"}:
                        raise Reject("PATH_STATE_MISMATCH", "replace target is absent or not a regular blob")
                    if current.get("sha") != change["expected_blob_sha"]:
                        raise Reject("PATH_STATE_MISMATCH", "replace target does not match expected_blob_sha")
                blob = self.api.request("GET", f"/git/blobs/{change['blob_sha']}") or {}
                if blob.get("sha") != change["blob_sha"] or blob.get("encoding") != "base64":
                    raise Reject("BLOB_NOT_FOUND", "candidate Git blob is unavailable")
                data = base64.b64decode(blob.get("content", ""), validate=False)
                if git_blob_sha(data) != change["blob_sha"]:
                    raise Reject("BLOB_NOT_REGULAR", "candidate object does not verify as the requested Git blob")
                validate_public_blob(data)

            branch_path = urllib.parse.quote(request["publication_branch"], safe="/")
            try:
                self.api.request("GET", f"/git/ref/heads/{branch_path}")
                raise Reject("BRANCH_EXISTS", "scoped publication branch already exists without an exact replay result")
            except RuntimeError as exc:
                if "failed with 404" not in str(exc):
                    raise

            if (((self.api.request("GET", "/git/ref/heads/main") or {}).get("object") or {}).get("sha")) != request["expected_base"]:
                raise Reject("EXPECTED_HEAD_MISMATCH", "protected main changed before publication mutation")
            new_tree = self.api.request("POST", "/git/trees", {
                "base_tree": tree_sha,
                "tree": [{"path": c["path"], "mode": "100644", "type": "blob", "sha": c["blob_sha"]} for c in request["changes"]],
            }) or {}
            new_tree_sha = new_tree.get("sha")
            if not _sha(new_tree_sha):
                raise Reject("INTERNAL_ERROR", "candidate tree creation returned no exact SHA")
            new_commit = self.api.request("POST", "/git/commits", {
                "message": f"historical-ledger: {request['request_id']}\n\nHWM-Ledger-Request-Id: {request['request_id']}\nHWM-Ledger-Request-Fingerprint: {fp}",
                "tree": new_tree_sha,
                "parents": [request["expected_base"]],
            }) or {}
            new_head = new_commit.get("sha")
            if not _sha(new_head):
                raise Reject("INTERNAL_ERROR", "candidate commit creation returned no exact SHA")
            if (((self.api.request("GET", "/git/ref/heads/main") or {}).get("object") or {}).get("sha")) != request["expected_base"]:
                raise Reject("EXPECTED_HEAD_MISMATCH", "protected main changed before scoped ref creation")
            self.api.request("POST", "/git/refs", {"ref": f"refs/heads/{request['publication_branch']}", "sha": new_head})
            pr = self.api.request("POST", "/pulls", {
                "title": f"Historical ledger publication {request['request_id']}",
                "head": request["publication_branch"],
                "base": DEFAULT_BRANCH,
                "body": f"Generated historical-ledger publication. Publisher does not merge this PR. Exact request id: `{request['request_id']}`.",
            }) or {}
            pr_number = pr.get("number")
            if not isinstance(pr_number, int):
                raise Reject("INTERNAL_ERROR", "scoped PR creation returned no number")

            self.api.request("POST", f"/actions/workflows/{CI_WORKFLOW}/dispatches", {
                "ref": request["publication_branch"],
                "inputs": {"request_id": request["request_id"], "expected_head": new_head},
            })
            run_id = None
            for _ in range(25):
                runs = self.api.request("GET", f"/actions/workflows/{CI_WORKFLOW}/runs?event=workflow_dispatch&branch={urllib.parse.quote(request['publication_branch'], safe='')}&per_page=20") or {}
                for run in runs.get("workflow_runs", []):
                    if run.get("head_sha") == new_head and run.get("event") == "workflow_dispatch" and run.get("path") == CI_PATH:
                        run_id = run.get("id")
                        break
                if isinstance(run_id, int):
                    break
                time.sleep(1)
            if not isinstance(run_id, int):
                raise Reject("CI_DISPATCH_FAILED", "explicit bootstrap CI dispatch could not be associated with exact candidate head")
            return {
                "schema": RESULT_SCHEMA,
                "request_id": request["request_id"],
                "status": "success",
                "repository": REPOSITORY,
                "transport_issue": TRANSPORT_ISSUE,
                "expected_base": request["expected_base"],
                "publication_branch": request["publication_branch"],
                "request_fingerprint": fp,
                "idempotent_replay": False,
                "commit_sha": new_head,
                "pr_number": pr_number,
                "ci_dispatch": {"workflow": CI_WORKFLOW, "run_id": run_id, "head_sha": new_head, "required_check": REQUIRED_CHECK},
                "error": None,
            }
        except Reject as exc:
            return error_result(raw, exc.code, exc.message, fp=fingerprint(raw))
        except Exception:
            return error_result(raw, "INTERNAL_ERROR", "publisher encountered a sanitized internal failure", fp=fingerprint(raw))


def cleanup(event: dict[str, Any], api: GitHub) -> None:
    pr = event.get("pull_request") or {}
    if pr.get("merged") is True or (pr.get("base") or {}).get("ref") != DEFAULT_BRANCH:
        return
    head = pr.get("head") or {}
    repo = head.get("repo") or {}
    branch = head.get("ref")
    if repo.get("full_name") != REPOSITORY or not isinstance(branch, str) or not branch.startswith(BRANCH_PREFIX):
        return
    api.request("DELETE", f"/git/refs/heads/{urllib.parse.quote(branch, safe='/')}")


def preflight(event: dict[str, Any]) -> dict[str, str]:
    comment = event.get("comment") or {}
    issue = event.get("issue") or {}
    repo = event.get("repository") or {}
    author = comment.get("user") or {}
    should = (
        issue.get("number") == TRANSPORT_ISSUE and not issue.get("pull_request") and repo.get("full_name") == REPOSITORY
        and author.get("login") == ALLOWED_AUTHOR["login"] and author.get("id") == ALLOWED_AUTHOR["id"]
    )
    if should:
        try:
            raw = json.loads(comment.get("body", ""))
            should = isinstance(raw, dict) and raw.get("schema") == REQUEST_SCHEMA
        except json.JSONDecodeError:
            should = False
    return {"should_run": "true" if should else "false", "concurrency_key": "historical-ledger"}


def _outputs(values: dict[str, str]) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if not path:
        for key, value in values.items():
            print(f"{key}={value}")
        return
    with open(path, "a", encoding="utf-8") as handle:
        for key, value in values.items():
            handle.write(f"{key}={value}\n")


def main(argv: list[str]) -> int:
    if len(argv) != 3 or argv[1] not in {"preflight", "publish", "cleanup"}:
        print("usage: historical_ledger_publisher.py {preflight|publish|cleanup} EVENT_JSON", file=sys.stderr)
        return 2
    with open(argv[2], "r", encoding="utf-8") as handle:
        event = json.load(handle)
    if argv[1] == "preflight":
        _outputs(preflight(event))
        return 0
    token = os.environ.pop("HWM_CONTEXT_PUBLISHER_TOKEN", None)
    if not token:
        print("publisher job token unavailable", file=sys.stderr)
        return 2
    api = GitHub(token)
    if argv[1] == "cleanup":
        cleanup(event, api)
        return 0
    result = Publisher(api).publish(event)
    if result is not None:
        api.request("POST", f"/issues/{TRANSPORT_ISSUE}/comments", {"body": canonical_json(result)})
        print(f"publish_status={result['status']} request_id={result['request_id']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
